services:
  # App Node (Express)
  app:
    build:
      context: ./main-api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

    command: npm run start
    depends_on:
      - fastapi
      - osrm

  # API Python (FastAPI)
  fastapi:
    build:
      context: ./routes-api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./routes-api/.env.production

  # OSRM
  osrm:
    build:
      context: ./osrm
      dockerfile: Dockerfile
    container_name: osrm-guatemala
    ports:
      - "5000:5000"
    volumes:
    - ./osrm:/data