FROM python:3.11
WORKDIR /usr/src/app

# Crear un usuario no root que tenga el mismo UID que el usuario host (Evitar error de privilegios)
RUN addgroup --gid 1000 appgroup && \
    adduser --uid 1000 --gid 1000 --disabled-password --gecos "" appuser

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

USER appuser

# Montar código en runtime, no copiar aquí
EXPOSE 8000
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--no-access-log"]
