FROM node:22-alpine

# Crear directorio de trabajo
WORKDIR /usr/src/app

# Instalar dependencias globales
RUN npm install -g nodemon tsx

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar dependencias
RUN npm install --include=dev

# Copiar el resto del código fuente
COPY . .

# Exponer puerto
EXPOSE 3000

# Comando de inicio
CMD ["npm", "run", "dev-docker"]
