EARTH_RADIUS_KM = 6371.0088
MATCHED_RUN_POINTS_COLLECTION = "matchedrunpoints"
SIMPLIFIED_RUN_POINTS_COLLECTION = "simplifiedrunpoints"
ROUTE_COLLECTION = "routes"
RUN_SCORES_COLLECTION = "runscores"
SEARCH_POINTS_MAX_RADIUS = 1000
RDP_EPSILON_M = 10
DTW_WINDOW_PERCENTAGE = 0.4

# h3 geoindex
H3_ROUTE_EDGE_RESOLUTION = 9
H3_ROUTE_EDGE_MAX_K_NEIGHBORS = 1
H3_MATCHED_POINT_SEARCH_RESOLUTION = 10
H3_MATCHED_POINT_SEARCH_MAX_K_NEIGHBORS = 1

# get_matched_runs_with_most_coincidences geoindex batching
GEOINDEX_BATCH_SIZE = 500
MAX_PARALLEL_GEOINDEX_BATCHES = 5

# Compare route prediction batching
MAX_PARALLEL_PREDICTION_BATCHES = 5
COMPARATION_LOW_THRESHOLD = 0.02

# Máximo para considerar un tramo final de ruta
MAX_ROUTE_LAST_SEGMENT_DISTANCE_M = 1000.0

# Comparación de tramo final de ruta para desvios
ROUTE_DEVIATION_COMPARISON_THRESHOLD = 0.05
DTW_WINDOW_PERCENTAGE_SHORT_ROUTES = 1